<a href="https://colab.research.google.com/github/babaroscopy/ML/blob/main/ML_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import matplotlib.image as mpimg
from sklearn import tree
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
%matplotlib inline 

In [2]:
df=pd.read_csv("wfp_food_prices_pakistan.csv", delimiter=",")
df.shape

(7663, 17)

In [3]:
del df['default']

In [4]:
df.dropna(inplace=True)
df.head(4)

date                cmname unit            category  price currency  \
1  2004-01-15  Wheat flour - Retail   KG  cereals and tubers   13.0      PKR   
2  2004-02-15  Wheat flour - Retail   KG  cereals and tubers   13.0      PKR   
3  2004-03-15  Wheat flour - Retail   KG  cereals and tubers  14.25      PKR   
4  2004-04-15  Wheat flour - Retail   KG  cereals and tubers   12.5      PKR   

    country      admname adm1id mktname  mktid cmid  ptid  umid catid  \
1  Pakistan  Balochistan   2272  Quetta  295.0   58  15.0   5.0     1   
2  Pakistan  Balochistan   2272  Quetta  295.0   58  15.0   5.0     1   
3  Pakistan  Balochistan   2272  Quetta  295.0   58  15.0   5.0     1   
4  Pakistan  Balochistan   2272  Quetta  295.0   58  15.0   5.0     1   

            sn  
1  295_58_15_5  
2  295_58_15_5  
3  295_58_15_5  
4  295_58_15_5

In [5]:
from sklearn import preprocessing
label_enco = preprocessing.LabelEncoder()
d = df.select_dtypes(include=['object'])
for i in d.columns:
    df[i]=label_enco.fit_transform(df[i])

In [6]:
Y=df['price']
del df['price']
X=df

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [10]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, Y, test_size=0.3, random_state=3)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='lbfgs')
LR.fit(X_trainset,y_trainset)
yhat = LR.predict(X_testset)
print("Accuracy: ", metrics.accuracy_score(y_testset, yhat))

Accuracy:  0.06916050456720313


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_testset, yhat))

              precision    recall  f1-score   support

           0       0.07      1.00      0.13        52
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         3
          34       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         5
          48       0.00      0.00      0.00         1
          49       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_testset, yhat))

[[52  0  0 ...  0  0  0]
 [ 2  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
